/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdarg.h>
#include "stm32f407xx.h"
#include "uart2.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void enable_configure_pins_init() {
  // Set bit 0 in AHB1 bus to enable GPIOA clock. Note: this enables clock for PA0 - PA15
  RCC_AHB1ENR |= (1 << 0);
  // Set bit 3 in AHB1 bus to enable GPIOD clock. Note: this enables clock for PD0 - PD15
  RCC_AHB1ENR |= (1 << 3);
  // set bit 17 in the APB1 bus to enable USART2 clock
  RCC_APB1ENR |= (1 << 17);
  // Readback after clock enable (force CPU to wait for write to complete)
  volatile unsigned int tmp = RCC_AHB1ENR; (void) tmp; // void tmp tells compiler to ignore unused var

  GPIOA_MODER &= ~(0x3 << 4); // clear bits [5:4] for PA2 (USART2_TX)
  GPIOA_MODER &= ~(0x3 << 6); // clear bits [7:6] for PA3 (USART2_RX)
  GPIOA_MODER |= (0x2 << 4); // set PA2 to 10 (alternate function mode)
  GPIOA_MODER |= (0x2 << 6); // set PA3 to 10 (alternate function mode) NOTE: not using yet

  GPIOA_AFRL &= ~(0xF << 8); // clear bits [11:8] for AFRL2 --> do we need to clear these bits?
  GPIOA_AFRL |= (0x7 << 8); // set AFRL2 to AF7 (USART2_TX)
  GPIOA_AFRL &= ~(0xF << 12); // clear bits [15:12] for AFRL3
  GPIOA_AFRL |= (0x7 << 12); // set AFRL3 to AF7 (USART2_RX) NOTE: not using yet
}

/* delay_ms(1000) produces roughly 1 second delay (rough calibration for 16 MHz clock) */
static void delay_ms(volatile uint32_t ms) {
  while (ms--) {
    // NOTE: at -O0 with volatile, each loop iteration costs several cycles, not just one NOP
    for (volatile uint32_t i = 0; i < 4000; ++i) { __asm__("nop"); }
  }
}

int main(void)
{
  enable_configure_pins_init(); // enable clocks and configure pins

  // set bits 24-30 to configure pins 12-15 (LEDs) of GPIOD to "general purpose output mode"
  for (int pin = 12; pin <=15; pin++) {
    GPIOD_MODER |= (1 << (pin * 2));
  }

  USART2_BRR = 0x008B; // USARTDIV = 16 MHz / (16 * 115200) = 8.6805. mantissa = 0x0080, fraction = 0xB (0.6805 * 16). write directly into register
  USART2_CR1 |= (1 << 13) | (1 << 3); // enable UE (USART Enable) and TE (Transmitter Enable)
  delay_ms(500);
  uart2_write_hex(USART2_SR);
  
  // create LED bitmask array
  const uint32_t leds[] = { (1U << 12), (1U << 13), (1U << 14), (1U << 15) };
  
  // Loop forever
	while(1) {
    for (int i = 0; i < 4; ++i) {
        // reset all four pins (write 1s to upper half of BSRR to reset)
        GPIOD_BSRR = (leds[0] << 16) | (leds[1] << 16) | (leds[2] << 16) | (leds[3] << 16);
        // set only the 'chosen' LED
        GPIOD_BSRR = leds[i];
        uart2_printf("LED %d SR=%x msg=%s\r\n", i, USART2_SR, "test");
        delay_ms(200);
    }
  }
}
